---
- name: Install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - certbot
    - python3-certbot-apache
  when: letsencrypt_ssl

- name: Install SSL
  become: yes
  shell: certbot --authenticator standalone --installer apache --pre-hook "service apache2 stop" --post-hook "service apache2 start" --non-interactive --agree-tos --email {{ project_contact_email }} --domains {{ host }},www.{{ host }}
  when: letsencrypt_ssl
