ansibleCopyrightNameVar: project_developer
ansibleRelativeDir: ansible
branchName: main
copyrightName: Helium Edu
tagRootRelease: false
gitProject: git@github.com:HeliumEdu
hostProvisionCommand: sudo apt-get update && sudo apt-get install -y python && sudo
  apt-get -y autoremove
projects:
- platform
- frontend
- cluster-tests
- frontend-legacy
releaseProjects:
- platform
- cluster-tests
- frontend-legacy
projectsRelativeDir: projects
remoteName: origin
serverBinFilename: bin/runserver
updateCopyrightYear: false
versionInfo:
  path: conf/configs/common.py
  project: platform
