sudo: required
dist: trusty
language: python
python:
- '3.6'
install:
- echo "deb https://download.virtualbox.org/virtualbox/debian trusty contrib" | sudo tee -a /etc/apt/sources.list
- wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
- wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
- sudo apt-get update
- sudo apt-get install -y virtualbox-5.2
- wget https://releases.hashicorp.com/vagrant/2.0.2/vagrant_2.0.2_x86_64.deb
- sudo dpkg -i vagrant_2.0.2_x86_64.deb
- python -m pip install -r requirements.txt
script:
- make env test