---
- name: Install repository
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/apache2'
    state: present
    update_cache: yes
    mode: 0644

- name: Install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apache2
    - libapache2-mod-wsgi

- name: Creates SSL directory
  become: yes
  file:
    path: /etc/apache2/ssl
    state: directory

- name: Enable WSGI
  become: yes
  apache2_module:
    name: wsgi
    state: present

- name: Enable Rewrite
  become: yes
  apache2_module:
    name: rewrite
    state: present

- name: Enable SSL
  become: yes
  apache2_module:
    name: ssl
    state: present

- name: Enable default site
  become: yes
  command: a2ensite 000-default
  notify: reload apache

- name: Disable default SSL site
  become: yes
  command: a2dissite default-ssl
  notify: reload apache

- name: Apache user
  become: yes
  replace:
    dest: /etc/apache2/envvars
    regexp: '^export APACHE_RUN_USER=www-data$'
    replace: 'export APACHE_RUN_USER=ubuntu'
    backup: yes
  notify: restart apache
  tags:
     - envvars

- name: Ensure started
  become: yes
  service:
    name: apache2
    state: started
