---
project_id: "helium"

project_root: "/srv/{{ project_id }}"

project_developer: "Helium Edu"
project_name: "Helium Student Planner"
project_tagline: "Lightening Your Course Load"

project_admin_email: "admin@heliumedu.com"
project_contact_email: "contact@heliumedu.com"

frontend_root: "{{ project_root }}/frontend"
platform_root: "{{ project_root }}/platform"

platform_venv: "/usr/local/venvs/{{ project_id }}_platform"

platform_db_name: "platform_{{ domain_environment }}"

platform_num_workers: 2

default_env_vars:
  ENVIRONMENT: "{{ domain_environment }}"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  PROJECT_DEVELOPER: "{{ project_developer }}"
  PROJECT_ID: "{{ project_id }}"
  PROJECT_NAME: "{{ project_name }}"
  PROJECT_TAGLINE: "{{ project_tagline }}"
  PROJECT_ADMIN_EMAIL: "{{ project_admin_email }}"
  PROJECT_CONTACT_EMAIL: "{{ project_contact_email }}"
  PROJECT_SUPPORT_URL: "https://heliumedu.uservoice.com"
  PROJECT_APP_HOST: "{{ frontend_host_protocol }}{{ frontend_host }}"
  PROJECT_API_HOST: "{{ platform_host_protocol }}{{ platform_host }}"
  PLATFORM_VENV: "{{ platform_venv }}"
  PLATFORM_HOME_DIR: "{{ platform_root }}"
  PLATFORM_ALLOWED_HOSTS: "{{ platform_host }} {{ platform_host_alias }} {{ ip_address }}"
  PLATFORM_DB_NAME: "{{ platform_db_name }}"
  PLATFORM_DB_HOST: "{{ platform_db_host }}"
  PLATFORM_EMAIL_HOST: "email-smtp.us-east-1.amazonaws.com"
  PLATFORM_EMAIL_PORT: 587
  PLATFORM_AWS_S3_STATIC_BUCKET_NAME: "heliumedu.{{ domain_environment }}.static"
  PLATFORM_AWS_S3_MEDIA_BUCKET_NAME: "heliumedu.{{ domain_environment }}.media"
