---
project_root: "/srv/helium"

project_admin_email: "admin@heliumedu.com"
project_contact_email: "contact@heliumedu.com"

platform_root: "{{ project_root }}/platform"

platform_db_name: "platform_{{ domain_environment }}"

default_env_vars:
  ENVIRONMENT: "{{ domain_environment }}"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  PROJECT_NAME: "Helium Student Planner"
  PROJECT_TAGLINE: "Lightening Your Course Load"
  PROJECT_ADMIN_EMAIL: "{{ project_admin_email }}"
  PROJECT_CONTACT_EMAIL: "{{ project_contact_email }}"
  PLATFORM_HOST: "{{ platform_host_protocol }}{{ platform_host }}"
  PLATFORM_HOME_DIR: "{{ platform_root }}"
  PLATFORM_ALLOWED_HOSTS: "{{ platform_host }} {{ platform_host_alias }} {{ ip_address }}"
  PLATFORM_DB_NAME: "{{ platform_db_name }}"
  PLATFORM_DB_HOST: "{{ platform_db_host }}"
  PLATFORM_EMAIL_HOST: "email-smtp.us-east-1.amazonaws.com"
  PLATFORM_EMAIL_PORT: 587
  PLATFORM_AWS_S3_STATIC_BUCKET_NAME: "heliumedu.{{ domain_environment }}.static"
  PLATFORM_AWS_S3_MEDIA_BUCKET_NAME: "heliumedu.{{ domain_environment }}.media"
