---
- name: Install Graphite packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libapache2-mod-wsgi

- name: Pip dependencies
  become: yes
  pip:
    name: PyMySQL
    version: 0.7.10

- name: Create Grafana database
  become: yes
  mysql_db:
    name: grafana_{{ domain_environment }}
    state: present
    login_host: "{{ platform_db_host }}"
    login_user: "{{ platform_db_user }}"
    login_password: "{{ platform_db_password }}"
    encoding: utf8
    collation: utf8_general_ci

- name: Grafana conf folder
  become: yes
  file:
    path: /etc/grafana
    state: directory
    mode: "2777"
    owner: "root"
    group: "root"

- name: Setup Grafana conf
  template:
    src: "grafana.ini"
    dest: "/etc/grafana/grafana.ini"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  vars:
    server_root_url: "http://{{ grafana_host }}"
    database_url: "mysql://{{ platform_db_user }}:{{ platform_db_password }}@{{ platform_db_host }}:3306/grafana_{{ domain_environment }}"
    security_admin_password: "{{ grafana_admin_password }}"
  tags:
     - conf

- name: Install Grafana repository
  become: yes
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/stable/debian/ jessie main'
    state: present
    update_cache: yes
    mode: 0644

- name: Install Grafana repository key
  become: yes
  apt_key:
    url: 'https://packagecloud.io/gpg.key'
    state: present

- name: Install Grafana packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - grafana

- name: Enable proxy
  become: yes
  apache2_module:
    name: proxy
    state: present

- name: Enable proxy
  become: yes
  apache2_module:
    name: proxy_http
    state: present

- name: Enable proxy
  become: yes
  apache2_module:
    name: headers
    state: present

- name: Setup Apache conf
  template:
    src: "grafana.apache.conf"
    dest: "/etc/apache2/sites-available/grafana.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  vars:
    url: "{{ grafana_host }}"
  notify: reload apache
  tags:
     - conf

- name: Enable Grafana site
  become: yes
  command: a2ensite grafana
  notify: reload apache

- name: Ensure Grafana started
  become: yes
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Restart Apache
  become: yes
  service:
    name: apache2
    state: restarted

- name: Check if Graphite datasource already exists
  uri:
    url: http://{{ grafana_host }}/api/datasources/name/Graphite
    user: "admin"
    password: "{{ grafana_admin_password }}"
    force_basic_auth: yes
  register: grafana_graphite
  failed_when: false
  changed_when: false

- name: Enable Graphite datasource
  uri:
    url: http://{{ grafana_host }}/api/datasources
    method: "POST"
    user: "admin"
    password: "{{ grafana_admin_password }}"
    body:
      name: "Graphite"
      type: "graphite"
      url: "http://{{ graphite_host }}"
      access: "proxy"
      isDefault: true
    force_basic_auth: yes
    status_code: 200
    body_format: json
  when: grafana_graphite.status == 404