---
- include_tasks: init.yml

- name: Set code directory
  set_fact:
    code_directory: "{{ project_root }}/platform"
  tags:
    - code
    - migrate

- include_tasks: clone.yml
  when: clone_code is undefined or clone_code
  tags:
    - code
    - migrate

- include_tasks: install.yml
  tags:
    - code
    - migrate

- include_tasks: cleanup.yml
  when: clone_code is undefined or clone_code
  tags:
    - code

- name: Ensure Apache is reloaded, as we just swapped out code
  become: yes
  service:
    name: apache2
    state: reloaded
  tags:
    - code
