---
- name: Ensure staging directory doesn't exist
  file:
    path: "{{ code_directory }}"
    state: absent

- name: Download artifact
  get_url:
    url: "https://github.com/HeliumEdu/frontend/archive/{{ platform_code_version | default('master') }}.tar.gz"
    dest: "{{ project_root }}/{{ platform_code_version | default('master') }}.tar.gz"

- name: Extract artifact to staging directory
  unarchive:
    src: "{{ project_root }}/{{ platform_code_version | default('master') }}.tar.gz"
    dest: "{{ project_root }}"
    remote_src: yes

- name: Move extracted to staging directory
  command: "mv {{ project_root }}/frontend-{{ platform_code_version | default('master') }} {{ code_directory }}"

- name: Delete artifact
  file:
    path: "{{ project_root }}/{{ platform_code_version | default('master') }}.tar.gz"
    state: absent