---
- name: SSL certificate
  become: yes
  copy:
    src: "../../../private/ssl/apache.{{ domain_environment }}.{{ frontend_host }}.crt"
    dest: "/etc/apache2/ssl/apache.crt"
  notify: restart apache
  when: letsencrypt_ssl is undefined or not letsencrypt_ssl
  tags:
     - ssl

- name: SSL key
  become: yes
  copy:
    src: "../../../private/ssl/apache.{{ domain_environment }}.{{ frontend_host }}.key"
    dest: "/etc/apache2/ssl/apache.key"
  notify: restart apache
  when: letsencrypt_ssl is undefined or not letsencrypt_ssl
  tags:
     - ssl

- name: SSL ca-bundle
  become: yes
  copy:
    src: "../../../private/ssl/apache.{{ domain_environment }}.{{ frontend_host }}.ca-bundle"
    dest: "/etc/apache2/ssl/apache.ca-bundle"
  notify: restart apache
  when: letsencrypt_ssl is undefined or not letsencrypt_ssl
  tags:
     - ssl

- name: Setup static Apache conf
  template:
    src: "../../apache/templates/static.conf"
    dest: "/etc/apache2/sites-available/{{ project_id }}-frontend.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  become: yes
  vars:
    url: "{{ frontend_host }}"
    alias_urls: "{{ frontend_host_alias }}"
    srv_dir: "{{ frontend_root }}"
    serve_local: "{{ project_serve_local | default(False) }}"
    # TODO: when the frontend is migrated to React, simply remove this line to serve a single-page application
    serve_from_index: False
  notify: reload apache
  tags:
     - conf

- name: Enable site conf
  become: yes
  command: "a2ensite {{ project_id }}-frontend"
  notify: reload apache

- name: Apache environment variables
  become: yes
  lineinfile:
    dest: /etc/apache2/envvars
    line: "export {{ item.key }}=\"{{ item.value }}\""
    regexp: "export {{ item.key }}="
  with_dict: "{{ env_vars }}"
  notify: reload apache
  tags:
     - envvars

- name: Generate SSL
  include_role:
    name: letsencrypt
  vars:
    host: "{{ frontend_host }}"
  when: letsencrypt_ssl is defined and letsencrypt_ssl
  tags:
    - ssl

- name: Create directory
  file:
    path: "{{ project_root }}/frontend"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Set code directory
  set_fact:
    code_directory: "{{ project_root }}/frontend_stage"
  tags:
    - code
    - migrate

- name: Set code directory
  set_fact:
    code_directory: "{{ project_root }}/frontend"
  tags:
    - code
    - migrate
  when: domain_environment == "devbox"

- import_tasks: download.yml
  when: download_code is undefined or download_code
  tags:
    - code
    - migrate

- import_tasks: install.yml
  tags:
    - code
    - migrate

- import_tasks: cleanup.yml
  when: download_code is undefined or download_code
  tags:
    - code

- name: Ensure Apache is reloaded
  become: yes
  service:
    name: apache2
    state: reloaded
  tags:
    - code
