---
- name: Install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - python-pip
    - python-dev
    - build-essential

- name: Get latest version
  become: yes
  shell: "pip install --upgrade pip"
