---
- name: Install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - python-pip
    - python-dev
    - build-essential

- name: Get latest version
  become: yes
  shell: "pip install --upgrade pip"

- name: Create venv directory
  become: yes
  file:
    path: "/usr/local/venvs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
