---
- name: Copy worker conf
  template:
    src: "celeryworker.conf"
    dest: "/etc/supervisor/conf.d/celeryworker.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  vars:
    root_dir: "{{ platform_root }}"
  with_dict: "{{ env_vars }}"
  become: yes
  notify: update supervisor
  tags:
     - conf

- name: Ensure Celery log dir is present
  become: yes
  file:
    path: "/var/log/supervisor"
    state: directory
    owner: root
    group: root
    mode: 0755