- name: Get local username
  local_action: "command whoami"
  register: local_username

- name: Get revision from tag
  local_action: "command git -C {{ playbook_dir }}/../projects/{{ rollbar_project }} rev-list -n 1 {{ build_version | default('main') }}"
  register: project_tag_revision

- name: Rollbar deploy
  rollbar_deployment:
    token: "{{ rollbar_server_access_token }}"
    environment: "{{ domain_environment }}"
    user: "{{ local_username.stdout }}"
    revision: "{{ project_tag_revision.stdout }}"
    comment: "{{ rollbar_comment | default('') }}"