---
- name: DevBox Setup
  hosts: devbox
  roles:
    # Server setup
    - { role: common }

    # Infrastructure
    - { role: mysql }
    - { role: redis }
    - { role: supervisor }
    - { role: celeryworker }

    # StatsD
    - { role: collectd-agent }
    - { role: statsd-server }
    - { role: statsd-agent }

    # Projects
    - { role: project-platform }
    - { role: project-platform-build, tags: ["code"] }
  environment: "{{ env_vars }}"
