---
- name: DevBox Setup
  hosts: devbox
  roles:
    # Server setup
    - { role: common }

    # Infrastructure
    - { role: mysql }
    - { role: redis }
    - { role: supervisor }
    - { role: celeryworker }
    - { role: celerybeat }

    # StatsD
    - { role: collectd-agent }
    - { role: statsd-server }
    - { role: statsd-agent }

    # Projects
    - { role: helium-platform, clone_code: False }
  environment: "{{ env_vars }}"
