---
- name: DevBox Setup
  hosts: devbox
  roles:
    # Server setup
    - { role: common }

    # Infrastructure
    - { role: mysql }
    - { role: redis }
    - { role: supervisor }
    - { role: celeryworker }
    - { role: celerybeat }
    - { role: datadog.datadog, become: yes }

    # CI
    - { role: selenium }

    # Projects
    - { role: helium-platform, download_code: False }
    - { role: helium-frontend, download_code: False }
  vars:
    deploy_group: "devbox"
    datadog_api_key: "{{ project_datadog_api_key }}"
    datadog_config:
      tags: "devbox"
  environment: "{{ env_vars }}"
