---
- name: DevBox Setup
  hosts: devbox
  roles:
    # Server setup
    - { role: common }

    # Infrastructure
    - { role: mysql }
    - { role: redis }
    - { role: supervisor }
    - { role: celeryworker }
    - { role: celerybeat }

    # Metrics
    - { role: graphite }
    - { role: grafana }
    - { role: collectd-agent }
    - { role: statsd-agent }

    # Projects
    - { role: helium-platform, download_code: False }
    - { role: helium-frontend, download_code: False }
  environment: "{{ env_vars }}"
