---
- name: Install yuglify
  become: yes
  npm:
    global: yes
    name: yuglify

- name: Install
  make:
    chdir: "{{ project_root }}/platform"
    target: install
  when: platform_code_only is undefined or not platform_code_only

- name: Test
  make:
      chdir: "{{ project_root }}/platform"
      target: test

- name: Build
  make:
    chdir: "{{ project_root }}/platform"
    target: build
  when: platform_code_only is undefined or not platform_code_only

- name: Migrate
  make:
      chdir: "{{ project_root }}/platform"
      target: migrate
  when: platform_code_only is undefined or not platform_code_only

- name: Restart Apache
  become: yes
  service:
    name: apache2
    state: restarted
  when: platform_code_only is undefined or not platform_code_only

- include_role:
  name: letsencrypt
  when: letsencrypt_ssl is defined and (platform_code_only is undefined or not platform_code_only)
  tags:
    - ssl
