---
- name: restart grafana-server
  become: yes
  service:
    name: grafana-server
    state: restarted
    enabled: yes

- name: restart carbon-cache
  become: yes
  service:
    name: carbon-cache
    state: restarted
    enabled: yes