name: "Build Release"

run-name: "Build release ${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  release:
    name: Build Release

    env:
      FORCE_COLOR: 1
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PLATFORM: amd64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python "3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup git
        run: |
          git config --global user.name "GitHub Release Bot"
          git config --global user.email "<contact@alexlaird.com>"
      - name: Install GitHub SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_GITHUB }}
          known_hosts: ${{ secrets.KNOWN_HOSTS_GITHUB }}
          if_key_exists: replace
      - name: Install dependencies
        run: make install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cut release tags
        run: helium-cli build-release ${{ inputs.version }}
      - name: Build
        run: TAG_VERSION=${{ inputs.version }} make build
      - name: Publish artifacts
        run: TAG_VERSION=${{ inputs.version }} make publish
      - name: Dump Docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2