name: "CI Test"

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run CI tests
        run: |
          sleep 60
          curl -X POST https://api.github.com/repos/HeliumEdu/ci-tests/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
          --data '{"event_type": "Triggered from `deploy` Release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
